# Generated by Django 4.2 on 2023-05-18 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_favoritepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_favorite_users', to='posts.post', verbose_name='Пост'),
        ),
    ]
